# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [7]:
empty_arry=np.empty(10)
empty_arry

array([6.95331127e-310, 8.71831158e-066, 3.99553057e+252, 1.19775386e-311,
       9.91622887e-280, 7.44044291e-251, 9.94206105e-280, 4.16249484e-256,
       1.56745861e-313, 0.00000000e+000])

3. Create a vector with values ranging from 10 to 49

In [9]:
arang_arr=np.arange(10,50)
arang_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [10]:
np.shape(arang_arr)

(40,)

5. Print the type of the previous array in question 3

In [11]:
type(arang_arr)

numpy.ndarray

6. Print the numpy version and the configuration


In [333]:
print( np.__version__ )

print(np.show_config())


1.19.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [334]:
np.ndim(arang_arr)

1

8. Create a boolean array with all the True values

In [335]:
bool_arr = np.ones(10, dtype=bool)
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [336]:
arr2d = np.arange(20).reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

10. Create a three dimensional array



In [337]:
arr3d = np.arange(27).reshape(3,3,3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [338]:
arang_arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [340]:
import numpy as np
x = np.empty(10)
x[5] = 1
print(x)


[-4.04276121e+037  0.00000000e+000  0.00000000e+000  1.37399457e+221
  0.00000000e+000  1.00000000e+000 -2.43732822e+272  0.00000000e+000
  0.00000000e+000  6.59856406e+233]


13. Create a 3x3 identity matrix

In [50]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [343]:
arr = np.array([1, 2, 3, 4, 5] ,np.float)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [344]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [345]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],
            [7., 2., 12.]])
arr3 =arr1==arr2
arr3

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [361]:
arr=np.arange(0,10) 
arr=arr[arr%2!=0]
arr

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [362]:
arr[::]=-1
arr


array([-1, -1, -1, -1, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [363]:
arr = np.arange(10)
arr[5:9:]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [364]:
arr=np.ones(25,np.int).reshape(5,5)
arr
arr[1:-1,1:-1]=0
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [365]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1:-1,1:-1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [366]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[:1]=64
arr3d



array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [367]:
arr=np.arange(10).reshape(5,2)
arr[:1]

array([[0, 1]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [368]:
arr=np.arange(10).reshape(5,2)
arr[1:2]

array([[2, 3]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [369]:
arr=np.arange(10).reshape(2,5)
arr[:,3:4]




array([[3],
       [8]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [372]:
arr=np.array(np.random.randn(10,10)*10,dtype=np.int)
print(arr.max())
print(arr.min())


27
-21


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [373]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [375]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [376]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
mask=(names!="Will")
data[mask]


array([[-0.13071906,  1.3516627 ,  2.43650248, -1.39657997],
       [ 1.09228828,  0.09856833, -1.22541725,  0.32142336],
       [-1.19986302,  0.86671998,  0.54684051,  0.88936096],
       [-0.3826888 , -0.48021794, -0.90547975, -1.14791221],
       [ 0.81720261,  0.4631083 ,  0.29934506, -1.7798333 ]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [377]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
mask=((names!="Will") & (names!="Joe"))
data[mask]

array([[ 0.2917735 ,  1.8171477 , -2.60589746,  1.85386104],
       [-0.96021246, -1.42360798, -0.9236383 ,  0.30515031]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [378]:
arr=np.arange(1,16).reshape(5,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [379]:
arr3d=np.arange(1,17).reshape(2, 2, 4)
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [231]:
np.transpose(arr3d)

array([[[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]],

       [[ 4, 12],
        [ 8, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [380]:
arr=np.array(np.random.randn(10))
arr[arr<.5]=0
arr=np.sqrt(arr)
arr



array([0.88867311, 1.08885865, 1.28444314, 0.        , 0.        ,
       1.258901  , 0.81013873, 1.00974806, 0.        , 1.56402288])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [381]:
x=np.array(np.random.randn(12))
y=np.array(np.random.randn(12))
print (x)
print (y)
np.maximum(x, y)

[ 0.23315778 -1.11641845 -0.74198644  0.22665016 -0.07363802 -1.06918172
 -0.36224594 -1.05640779 -0.92747852 -3.0518454   0.80647773  1.91960045]
[-1.69825805 -0.66447576 -1.30727326 -1.57270714  0.49668195 -0.25295996
 -0.88246826  0.09091957  1.65698221  0.16178402  0.13743822  0.69816959]


array([ 0.23315778, -0.66447576, -0.74198644,  0.22665016,  0.49668195,
       -0.25295996, -0.36224594,  0.09091957,  1.65698221,  0.16178402,
        0.80647773,  1.91960045])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [382]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names
np.sort(np.unique(names))


array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [281]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [318]:
import numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = numpy.array([[10,10,10]])

sampleArray[:,2:3]=numpy.transpose(newColumn)

sampleArray

array([[34, 43, 10],
       [82, 22, 10],
       [53, 94, 10]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [319]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(y,x)

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [330]:
my_array=np.array(np.random.randn(20),dtype=np.int)
numpy.matrix.cumsum(my_array)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int32)